services:
  - type: web
    name: abacha-rasa-chatbot
    env: docker
    dockerfilePath: ./backend/rasa_chatbot/Dockerfile
    dockerContext: ./backend/rasa_chatbot
    plan: free
    healthCheckPath: /
    envVars:
      - key: RASA_LOG_LEVEL
        value: INFO
