-- Create delivery_routes table for route optimization
CREATE TABLE IF NOT EXISTS delivery_routes (
  id SERIAL PRIMARY KEY,
  merchant_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rider_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  route_coordinates JSONB NOT NULL,  -- Array of [latitude, longitude] coordinates
  total_distance_m INTEGER NOT NULL DEFAULT 0,  -- Total distance in meters
  order_ids INTEGER[] NOT NULL,  -- Array of order IDs in this route
  status VARCHAR(20) NOT NULL DEFAULT 'pending',  -- pending, active, completed, cancelled
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT delivery_routes_status_check CHECK (status IN ('pending', 'active', 'completed', 'cancelled')),
  CONSTRAINT delivery_routes_distance_check CHECK (total_distance_m >= 0),
  CONSTRAINT delivery_routes_orders_check CHECK (array_length(order_ids, 1) > 0)
);

-- Create indexes for better query performance
CREATE INDEX idx_delivery_routes_merchant_id ON delivery_routes(merchant_id);
CREATE INDEX idx_delivery_routes_rider_id ON delivery_routes(rider_id);
CREATE INDEX idx_delivery_routes_status ON delivery_routes(status);
CREATE INDEX idx_delivery_routes_created_at ON delivery_routes(created_at);
CREATE INDEX idx_delivery_routes_merchant_status ON delivery_routes(merchant_id, status);
CREATE INDEX idx_delivery_routes_rider_status ON delivery_routes(rider_id, status);

-- Create GIN index for order_ids array to support efficient array operations
CREATE INDEX idx_delivery_routes_order_ids ON delivery_routes USING GIN (order_ids);

-- Create trigger to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_delivery_routes_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_delivery_routes_timestamp
  BEFORE UPDATE ON delivery_routes
  FOR EACH ROW
  EXECUTE FUNCTION update_delivery_routes_updated_at();

-- Add comment to table
COMMENT ON TABLE delivery_routes IS 'Stores optimized delivery routes generated by route optimization algorithm';
COMMENT ON COLUMN delivery_routes.route_coordinates IS 'JSONB array of [lat, lon] coordinate pairs representing the delivery route';
COMMENT ON COLUMN delivery_routes.total_distance_m IS 'Total route distance in meters';
COMMENT ON COLUMN delivery_routes.order_ids IS 'Array of order IDs assigned to this route';
COMMENT ON COLUMN delivery_routes.status IS 'Route status: pending (created), active (in progress), completed (finished), cancelled (aborted)';
