-- Token PINs table for managing token credit top-ups
-- PINs are 17-digit codes generated by the token generation body

CREATE TABLE IF NOT EXISTS token_pins (
  id SERIAL PRIMARY KEY,
  pin_code VARCHAR(17) UNIQUE NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  is_used BOOLEAN DEFAULT FALSE,
  used_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  used_at TIMESTAMP,
  expires_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  created_by VARCHAR(100) DEFAULT 'SYSTEM'
);

-- Index for fast PIN lookup
CREATE INDEX idx_token_pins_pin_code ON token_pins(pin_code);
CREATE INDEX idx_token_pins_is_used ON token_pins(is_used);

-- Add comment
COMMENT ON TABLE token_pins IS 'Stores token credit PIN codes for customer top-ups';
COMMENT ON COLUMN token_pins.pin_code IS '17-digit PIN code generated by token generation body';
COMMENT ON COLUMN token_pins.amount IS 'Amount of token credits this PIN provides';
COMMENT ON COLUMN token_pins.is_used IS 'Whether this PIN has been redeemed';
COMMENT ON COLUMN token_pins.used_by IS 'User ID who redeemed this PIN';
COMMENT ON COLUMN token_pins.expires_at IS 'PIN expiration date (optional)';
